### ISSUE TITLE
Spark - No IPv4 Support

### ISSUE THREAD

**Issue by dineshchitlangia** [facebookresearch/DCPerf#30]
https://github.com/facebookresearch/DCPerf/blob/fd529033d1c01a3977f736d0fb351e5af02f9fb3/packages/spark_standalone/templates/nvme_tcp/setup_nvmet.py#L79

The nvme_tcp setup assumes IPv6 setup.

For IPv4 scenario, this won't work and needs to be modified.

**Comment by excelle08** [comment]
IPv4 support is added as we released v0.1.0, please feel free to try the latest version
