### ISSUE TITLE
HHVM-3.30 binary for Ubuntu

### ISSUE THREAD

**Issue by excelle08** [facebookresearch/DCPerf#50]
Due to upload size limit, we have to split the package into two. Therefore, if you are using Ubuntu and would like to install HHVM-3.30 for Mediawiki benchmark, please download [hhvm-3.30-multplatform-binary-ubuntu.tar.xz](https://github.com/facebookresearch/DCPerf/releases/download/hhvm/hhvm-3.30-multplatform-binary-ubuntu.tar.xz) in https://github.com/facebookresearch/DCPerf/releases/tag/hhvm

**Comment by CoolBlueSam** [comment]
Could you please include the link in the README?

**Comment by excelle08** [comment]
Fixed in [ce4d59d](https://github.com/facebookresearch/DCPerf/commit/ce4d59dfa06810c2f7005643568b233eae197330)
