### ISSUE TITLE
Django: parser module not found (Ubuntu 22.04)

### ISSUE THREAD

**Issue by CoolBlueSam** [facebookresearch/DCPerf#53]
While trying to run Django, it is showing parser module error. Seems like this module is deprecated after python3.9. 

Traceback (most recent call last):
  File "/DCPerf/benchmarks/django_workload/django-workload/client/./gen-urls-file", line 7, in <module>
    import parser
ModuleNotFoundError: No module named 'parser'

**Comment by excelle08** [comment]
Hello, thanks for bringing up this issue! We're working on fixing this. In the meantime you can workaround this problem by commenting out or remove `import parser` in line 7 of `benchmarks/django_workload/django-workload/client/gen-urls-file` since this module isn't actually used.

**Comment by CoolBlueSam** [comment]
Will do. Thanks!!

**Comment by excelle08** [comment]
Should be fixed in [f2b1981](https://github.com/facebookresearch/DCPerf/commit/f2b1981cfb493139351bb2b024ad25a6eb68f7d9), please feel free to try.
