### ISSUE TITLE
Enhancement request: Provide db_addr variable in "-r db" in Django

### ISSUE THREAD

**Issue by CoolBlueSam** [facebookresearch/DCPerf#54]
Currently when calling run for django, you are able to specify the db_addr {"db_addr": "<db-server-ip>"}

However while initializing the db, you cannot do it unless you do it via run.sh script directly (as mentioned in the documentation). Should be easy to add support for this variable for -r db option as well.

**Comment by excelle08** [comment]
Thanks for suggesting, sure we will add this option to the Benchpress command.

**Comment by excelle08** [comment]
This is done in [aa336f1](https://github.com/facebookresearch/DCPerf/commit/aa336f17231a16e96a2e1de980b4752a576c9981)
