### ISSUE TITLE
Question: List of needed files only

### ISSUE THREAD

**Issue by CoolBlueSam** [facebookresearch/DCPerf#56]
Hello,

So far I have installed django_workload_custom, tao_bench_autoscale and feedsim_autoscale. I noticed that the disk space usage is a lot. After installation is there a list of files that we don't need anymore that we can delete or just a list of bare minimum files we need to run these three workloads? 

I haven't been able to get hhvm for mediawiki working on ubuntu. After following all the steps, I still get error for libfribidi.so.0

**Comment by excelle08** [comment]
I checked the installer script `pour-hhvm.sh` and noticed it should install `libfribidi-dev`. If you see it missing, it might be because the `apt install` didn't complete successfully. Could you look at the output of `pour-hhvm.sh` and see if that's the case?

**Comment by excelle08** [comment]
Regarding disk space usage, you can delete `benchmarks/tao_bench/build-folly` to release about 14GB

**Comment by CoolBlueSam** [comment]
Thanks. 

I started with a clean build, and didn't see the lib error. So closing it.
