### ISSUE TITLE
meson error while installing video_transcode_bench_avt on Ubuntu

### ISSUE THREAD

**Issue by CoolBlueSam** [facebookresearch/DCPerf#58]
Seeing error with meson. Looks like it is called with unsupported attribute. 

/DCPerf/benchmarks/video_transcode_bench/ffmpeg_sources /DCPerf/benchmarks/video_transcode_bench /DCPerf
+ cd vmaf/libvmaf
+ meson setup _build --prefix=/DCPerf/benchmarks/video_transcode_bench/ffmpeg_build --default-library static --prefer-static --buildtype release
usage: meson [-h] {setup,configure,dist,install,introspect,init,test,wrap,subprojects,help,rewrite,compile,devenv} ...
meson: error: unrecognized arguments: --prefer-static
Traceback (most recent call last):
  File "/DCPerf/./benchpress_cli.py", line 16, in <module>
    main()
  File "/DCPerf/benchpress/cli/main.py", line 310, in main
    args.command.run(args, bp.jobs)
  File "/DCPerf/benchpress/cli/commands/install.py", line 75, in run
    install_benchmark(job.install_script, env=env)
  File "/DCPerf/benchpress/lib/util.py", line 89, in install_benchmark
    raise Exception(f"Failed to run '{cmd_str}'")
Exception: Failed to run 'bash -x ./packages/video_transcode_bench/install_video_transcode_bench.sh'

**Comment by YifanYuan3** [comment]
Hi @CoolBlueSam  thanks for raising the issue. This has been fixed. Please pull the latest commit and try again. Let us know if you have further questions.

**Comment by CoolBlueSam** [comment]
Thanks. It's working now.
